//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6_2_0320190016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public string nim { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string email { get; set; }
        public System.DateTime tgl_lahir { get; set; }
    }
}
